start: (artifact | trace | _NL)+

artifact: ARTIFACT name ":" _NL _INDENT (rule | _NL)* _DEDENT
rule: "attribute" name "is" PRESENCE [MULTIPLE] type [condition] _NL
    | "id" "is" type ["as" schema_value] _NL

trace: "trace" "from" name "to" target_list "is" PRESENCE ["via" TRACE_MODE] [condition] _NL
target_list: name ("or" name)*

condition: "if" [NOT] anchor
anchor: WORD
NOT: "not"

?type: "string" -> type_string
     | "integer" -> type_integer
     | "boolean" -> type_boolean
     | "reference" to_parent? -> type_reference
     | "enum" "[" value ("," value)* "]" -> type_enum

to_parent: "to" "parent"

?schema_value: unquoted_items | quoted_items

unquoted_items: (SCHEMA_PART | PLACEHOLDER | INVALID_PLACEHOLDER)+
quoted_items: "\"" (QUOTED_PART | PLACEHOLDER | INVALID_PLACEHOLDER)* "\""

PLACEHOLDER: /\{(atype|num(:\d+)?)\}/
INVALID_PLACEHOLDER: /\{[^}]+\}/

SCHEMA_PART: /[^ \t\n\r"{]+/
QUOTED_PART: /[^"{]+/

ARTIFACT: "artifact"
MULTIPLE: "multiple"
%import common.INT
?name: WORD
PRESENCE: "mandatory" | "optional"
TRACE_MODE: "commit" | "timestamp"
?value: ESCAPED_STRING | WORD

%import common.WORD
%import common.ESCAPED_STRING
%import common.WS_INLINE
%import common.SH_COMMENT
%ignore WS_INLINE
%ignore SH_COMMENT

%declare _INDENT _DEDENT
_NL: /(\r?\n[\t ]*)+/
